### ISSUE TITLE
Flyway migrate via command-line fails with "java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper"

### ISSUE THREAD

**Issue by rzanner** [flyway/flyway#3710]
###### Which version and edition of Flyway are you using?
9.20.1 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
In 9.20.0 everything works fine, but not in the latest 9.20.1.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Oracle 12 XE

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I am running "flyway migrate" and it fails with "java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper".

###### What did you expect to see?
I expected to see the list of successfully applied migrations (works in 9.20.0).

###### What did you see instead?
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.flywaydb.commandline.MavenVersionChecker.checkForVersionUpdates(MavenVersionChecker.java:60)
        at org.flywaydb.commandline.Main.main(Main.java:107)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 14 more

It seems that jackson-databind is missing in the lib/ or lib/aad/ folder.

**Comment by JasonLuo-Redgate** [comment]
Hi @rzanner , is your issue the same as https://github.com/flyway/flyway/issues/3705 ?

**Comment by rzanner** [comment]
Hi @JasonLuo-Redgate, no - the mentioned issue is about the Flyway docker container. It **might** be the same issue, though, but I haven't analyzed the other issue since it was closed already (and I don't know if the closing was correct or not).

**Comment by rzanner** [comment]
Ok - there it is. We seem to re-package the flyway-commandline-9.20.1.tar.gz for our deployment. 

Until now we cleaned the drivers folder, since we only want to deploy what's absolutely necessary in our environment. We also want to use the commercial Oracle driver instead of the one delivered by flyway.

What's the use of jackson-databind in the drivers/ folder (and not in the lib/ folder)? Why are there so many different library locations at all? :-/

**Comment by JasonLuo-Redgate** [comment]
Hi @rzanner ,
This directory has dependencies which are also required for the proper functionality of Flyway to occur. If you are wishing to add a JDBC driver which flyway does not provide to your Flyway instance, please create a separate directory and use the [-jarDirs](https://documentation.red-gate.com/fd/jar-dirs-184127510.html) parameter to allow flyway to load your JDBC driver.

PS: In the release notes of Flyway 9.20.1, we can see flyway-core now has a dependency on jackson-dataformat-toml.
https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html#9.20.1

**Comment by rzanner** [comment]
Hi @JasonLuo-Redgate, 
thank you for your response and the hints provided. Does the "-jarDirs" parameter take precedence over the packaged driver JARs?

Since flyway-core 9.20.1 now has a runtime dependency on jackson-toml (which has a runtime dependency on jackson-databind), I expect both of these JAR files to be in the lib/ folder rather than spread over the lib/ *and* the drivers/ folders.

However, I will close this issue now and will open a new one for the jackson-databind JAR to be required in the lib/ folder rather than the drivers/ folder...
