### ISSUE TITLE
Flyway shouldn't attempt to colorize the log if there is no System.console()

### ISSUE THREAD

**Issue by xdy** [flyway/flyway#2727]
###### Which version and edition of Flyway are you using?
6.3.1 community edition (via the official dockerfile)
The problem showed itself when we upgraded from 6.1.4 to 6.3.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using (type & version)?
DB2 11.5

###### Which operating system are you using?
Alpine linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
We do the following inside the docker image (in a CI environment)
set ANSIBLE_FORCE_COLOR=true
run flyway info

###### What did you expect to see?
The usual output of flyway info

###### What did you see instead?
  Exception in thread "main" java.lang.NoClassDefFoundError: org/fusesource/jansi/AnsiConsole
  	at org.flywaydb.commandline.ColorizedConsoleLog.install(ColorizedConsoleLog.java:36)
  	at org.flywaydb.commandline.ConsoleLogCreator.createLogger(ConsoleLogCreator.java:45)
  	at org.flywaydb.commandline.MultiLogCreator.createLogger(MultiLogCreator.java:39)
  	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:80)
  	at org.flywaydb.core.internal.util.ClassUtils.<clinit>(ClassUtils.java:35)
  	at org.flywaydb.core.internal.util.FeatureDetector.isSlf4jAvailable(FeatureDetector.java:91)
  	at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:39)
  	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:77)
  	at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:25)
  	at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:35)
  	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:77)
  	at org.flywaydb.commandline.Main.initLogging(Main.java:73)
  	at org.flywaydb.commandline.Main.main(Main.java:83)
  Caused by: java.lang.ClassNotFoundException: org.fusesource.jansi.AnsiConsole
  	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
  	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
  	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
  	... 13 more

###### Workaround
Unset ANSIBLE_FORCE_COLOR
Well, it ought to work, haven't had a chance to test it yet, and I don't really want to do that anyway.

###### Suggested fix
The problem seems to have been caused in commit https://github.com/flyway/flyway/commit/72cfe7db4a21a44001648ea8e00aef70849cf24d
Specifically by the following change:
-      if (System.console() == null) {
+        if (Color.NEVER.equals(color)) {

It seems to me that it is still useful to check if System.console() is null, in which case colorization is certainly not useful. I.e. I suggest that line 41 in ConsoleLogCreator be changed as follows:
-        if (Color.NEVER.equals(color)) {
+      if (System.console() == null && Color.NEVER.equals(color)) {

**Comment by MikielAgutu** [comment]
Fair point. I'll investigate. In the meantime you can specify the colorization behavior you would like by using the `color` option https://flywaydb.org/documentation/commandline/migrate#color

**Comment by juliahayward** [comment]
Will be fixed in the 6.3.2 release.
