### ISSUE TITLE
NoSuchMethodError PluginRegister.getExact when upgrading to 11.13.x and 11.14.x

### ISSUE THREAD

**Issue by lackovic** [flyway/flyway#4145]
When upgrading from version 11.12.0 to **11.13.1** I get the following error:

```
NoSuchMethodError: 'org.flywaydb.core.extensibility.Plugin org.flywaydb.core.internal.plugin.PluginRegister.getExact(java.lang.Class)'
``` 

Expected result: no errors are thrown.

Possibly related with https://github.com/flyway/flyway/issues/4140

**Comment by lackovic** [comment]
Mitigated with the following resolution strategy in `build.gradle`:

```groovy
configurations.configureEach {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        if (details.requested.group == 'org.flywaydb' &&
                details.requested.name.contains('flyway-core')) {
            details.useVersion '11.13.1'
            details.because 'flyway/issues/4145'
        }
    }
}
```

**Comment by JasonLuo-Redgate** [comment]
Hi @lackovic ,

Many thanks for reporting this issue to us. 

I’d like to understand more about your mitigation solution. I’m not sure I follow this setting — it looks like you pinned the version to `11.13.1`, but isn’t that the version that originally caused the issue?

**Comment by lackovic** [comment]
> isn’t that the version that originally caused the issue?

My understanding is that the issue is not in the version itself but in the version of the transitive dependency that it uses.

Looking at my application dependencies, without the earlier mentioned resolution strategy, I get:

```sh
$ ./gradlew dependencyInsight --dependency flyway

> Task :dependencyInsight
org.flywaydb:flyway-core:11.7.2 (selected by rule)
  Variant compile:
    | Attribute Name                 | Provided | Requested    |
    |--------------------------------|----------|--------------|
    | org.gradle.status              | release  |              |
    | org.gradle.category            | library  | library      |
    | org.gradle.libraryelements     | jar      | classes      |
    | org.gradle.usage               | java-api | java-api     |
    | org.gradle.dependency.bundling |          | external     |
    | org.gradle.jvm.environment     |          | standard-jvm |
    | org.gradle.jvm.version         |          | 21           |

org.flywaydb:flyway-core:11.13.1 -> 11.7.2
\--- org.flywaydb:flyway-database-postgresql:11.13.1
     \--- compileClasspath

org.flywaydb:flyway-database-postgresql:11.13.1 (selected by rule)
  Variant compile:
    | Attribute Name                 | Provided | Requested    |
    |--------------------------------|----------|--------------|
    | org.gradle.status              | release  |              |
    | org.gradle.category            | library  | library      |
    | org.gradle.libraryelements     | jar      | classes      |
    | org.gradle.usage               | java-api | java-api     |
    | org.gradle.dependency.bundling |          | external     |
    | org.gradle.jvm.environment     |          | standard-jvm |
    | org.gradle.jvm.version         |          | 21           |

org.flywaydb:flyway-database-postgresql:11.13.1
\--- compileClasspath
``` 

which seems to indicate that `org.flywaydb:flyway-database-postgresql:11.13.1` is incorrectly using `org.flywaydb:flyway-core:11.7.2` instead of `org.flywaydb:flyway-core:11.13.1`.

The resolution strategy above is forcing the application to use the version 11.13.1 wherever `org.flywaydb:flyway-core` is used as transitive dependency. Outcome after applying the resolution strategy:

```sh
$ ./gradlew dependencyInsight --dependency flyway

> Task :dependencyInsight
org.flywaydb:flyway-core:11.13.1
  Variant compile:
    | Attribute Name                 | Provided | Requested    |
    |--------------------------------|----------|--------------|
    | org.gradle.status              | release  |              |
    | org.gradle.category            | library  | library      |
    | org.gradle.libraryelements     | jar      | classes      |
    | org.gradle.usage               | java-api | java-api     |
    | org.gradle.dependency.bundling |          | external     |
    | org.gradle.jvm.environment     |          | standard-jvm |
    | org.gradle.jvm.version         |          | 21           |
   Selection reasons:
      - Selected by rule
      - Selected by rule: flyway/issues/4145

org.flywaydb:flyway-core:11.13.1
\--- org.flywaydb:flyway-database-postgresql:11.13.1
     \--- compileClasspath

org.flywaydb:flyway-database-postgresql:11.13.1 (selected by rule)
  Variant compile:
    | Attribute Name                 | Provided | Requested    |
    |--------------------------------|----------|--------------|
    | org.gradle.status              | release  |              |
    | org.gradle.category            | library  | library      |
    | org.gradle.libraryelements     | jar      | classes      |
    | org.gradle.usage               | java-api | java-api     |
    | org.gradle.dependency.bundling |          | external     |
    | org.gradle.jvm.environment     |          | standard-jvm |
    | org.gradle.jvm.version         |          | 21           |

org.flywaydb:flyway-database-postgresql:11.13.1
\--- compileClasspath
```

**Comment by lackovic** [comment]
The issue occurs when only `org.flywaydb:flyway-database-postgresql` is imported:

```groovy
implementation("org.flywaydb:flyway-database-postgresql:11.13.1")
``` 

In one application, where `flyway-core` is explicitly included, this issue is not occurring:

```groovy
implementation "org.flywaydb:flyway-core:11.13.1"
implementation "org.flywaydb:flyway-database-postgresql:11.13.1"
```

but this should not be necessary: importing the second should be enough, right @JasonLuo-Redgate?

**Comment by JasonLuo-Redgate** [comment]
Hi @lackovic ,

After investigating, I believe this issue is caused by recent code refactoring in the `flyway-core` and `flyway-database` classes related to `PluginRegister`. These changes are not binary-compatible, so the versions of `flyway-core` and `flyway-database` must now match exactly. 

You’ll need to explicitly specify matching implementations of both `flyway-core` and `flyway-database` in your gradle setting.

**Comment by lackovic** [comment]
@JasonLuo-Redgate thanks for looking into it.

While that workaround works, this dependency issue could trip up other users since the version relationship isn't obvious.

I'd suggest either:

1. Auto-import: have `flyway-database` automatically import a compatible `flyway-core` version
1. Explicit deps: remove the transitive dependency so users must declare both explicitly.

Either approach would prevent similar version conflicts. What's your preference?

**Comment by JasonLuo-Redgate** [comment]
This seems to be related to our recent release issue: Gradle `11.13.1` wasn’t published (the latest available is `11.13.0`):
https://plugins.gradle.org/plugin/org.flywaydb.flyway

However, `flyway-core` has been released at `11.13.1`, and `11.13.0` was a skipped release due to a technical issue.

Still under investigation.

**Comment by lackovic** [comment]
The problem is still present in `11.13.2`.

**Comment by WilliamL-RG** [comment]
Hi, I've tried replicating this with 11.13.2 but I have had not seen the same issues with the dependencies. This is the script I am running:

```
plugins{
    id "java"
    id "org.flywaydb.flyway" version "11.13.2"

}

dependencies {
    repositories {
        mavenCentral()
    }

    implementation "org.xerial:sqlite-jdbc:3.46.1.0"
    implementation "org.flywaydb:flyway-database-postgresql:11.13.2"
}

flyway {
    url = 'jdbc:sqlite:file:file.db'
    user = 'myUsr'
    password = 'mySecretPwd'
}
```

Could you share your `build.gradle` script so we can see what might be causing this

**Comment by lackovic** [comment]
@WilliamL-RG thanks for looking into this! 

One difference I can see with my script is that I am not using the `org.flywaydb.flyway` plugin, is that necessary? It doesn't seem to make a difference: after I add it the old version `11.7.2` of `flyway-core` is still used.

**Comment by lackovic** [comment]
**Steps to reproduce**
1. use [start.spring.io](https://start.spring.io/) to generate a new project
2. open `build.gradle`
3. add `implementation "org.flywaydb:flyway-database-postgresql:11.13.2"`
4. in terminal run `./gradlew dependencyInsight --dependency flyway-core`


**Expected result**

```
> Task :dependencyInsight
org.flywaydb:flyway-core:11.13.2 (selected by rule)
``` 

**Actual result**

```
> Task :dependencyInsight
org.flywaydb:flyway-core:11.7.2 (selected by rule)
```

**Comment by lackovic** [comment]
The problem is still present in `11.13.3`.

Edit: and `11.14.0` and `11.14.1`.

**Comment by lackovic** [comment]
@WilliamL-RG did you manage to replicate the issue? Do you need any more input from my side?

**Comment by WilliamL-RG** [comment]
Hi,
I was able to replicate this using the steps provided. 
I tested removing `io.spring.dependency-management` from the plugins and when I did this, the version of `flyway-core` was now `11.13.2`. Explicitly specifying `flyway-core` as a dependency also removes the version discrepancy from gradle.

**Comment by lackovic** [comment]
@WilliamL-RG thanks for the explanation. I understand this problem is caused by `io.spring.dependency-management` itself or by the incorrect way I was using it.

Eventually I managed to get everything working as expected by adding the following line to the `buildscript` block of my `build.gradle`:

```groovy
ext['flyway.version'] = '11.14.1'
```

and by removing the explicit version when importing `flyway-database-postgresql`:
```
implementation "org.flywaydb:flyway-database-postgresql"
``` 

This makes `io.spring.dependency-management` use the same version for both `flyway-database-postgresql` and `flyway-core`.

Another way to solve this is to just avoid specifying the Flyway version anywhere in `build.gradle` and let `io.spring.dependency-management` choose the right version, which will not be the latest version but it is guaranteed to be the same version for both `flyway-database-postgresql` and `flyway-core`.

Feel free to close this issue if you confirm my understanding and agree with this resolution.
