### ISSUE TITLE
S3Client class not found error when loading Configuration via Guice with 7.0.1

### ISSUE THREAD

**Issue by josephlbarnett** [flyway/flyway#2969]
###### Which version and edition of Flyway are you using?
7.0.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres 12

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Got a default `FluentConfiguration` object out of a guice injector (or tried to inject a `FluentConfiguration` into another class, but this demonstrates the issue minimally):
```
FluentConfiguration conf = Guice.createInjector().getInstance(FluentConfiguration.class)
```

###### What did you expect to see?
An object returned which would allow further configuration

###### What did you see instead?
```
Exception in thread "main" java.lang.NoClassDefFoundError: software/amazon/awssdk/services/s3/S3Client
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at com.google.inject.internal.DeclaredMembers.getDeclaredMethods(DeclaredMembers.java:40)
	at com.google.inject.spi.InjectionPoint.getDeclaredMethods(InjectionPoint.java:757)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:676)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:376)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:182)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:672)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:628)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:614)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:943)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:863)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:300)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:231)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:1084)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1116)
	at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:1078)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1131)
	at com.trib3.db.modules.FlywayModuleKt.main(FlywayModule.kt:32)
	at com.trib3.db.modules.FlywayModuleKt.main(FlywayModule.kt)
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.services.s3.S3Client
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 21 more
```

Seems to be caused by making the s3 dependency optional in d17dac86a93da0709b0a42e6ef57bb8d46dcc2a2 .   But with direct references to `S3Client`, the dependency is not fully optional?

**Comment by DoodleBobBuffPants** [comment]
Hi. Are you able to reproduce the issue without the injector (creating an instance of `FluentConfiguration` yourself)? The references in the configuration are required for when you do supply an `S3Client`, but they won't attempt to load the class unless the relevant methods are called. I believe this issue is caused by the injector, in which case it isn't a Flyway issue

**Comment by josephlbarnett** [comment]
yes, creating the `FluentConfiguration` directly through its constructor works properly and allows for `conf.load().migrate()` to run successfully.  Seems that guice doing reflection introspection on the class itself is what triggers the issue, which is also reproducible with this one line of code:
```
        Method[] methods = FluentConfiguration.class.getDeclaredMethods();
```

**Comment by walery** [comment]
I was also migrating my project to version 7.0.1 and faced similar issue. I just want to share my finding as this could be helpful to solve the issue.

Let's take a look to this code:

```java
import org.flywaydb.core.Flyway;

public class DbMigration {
  public static void main(String[] args) {
    Flyway.configure().load();
  }
}
```

Compiling this with java compiler (so file is called `DbMigration.java`) works without any issue.
Also executing is successful.

Trying same with by renaming the file to groovy (the file is now called `DbMigration.groovy` (no need to change the content, this is valid groovy code)).
The groovy version will compile without any issue.
But it's not possible to run this anymore. The reported error will occur:

```
Caused by: java.lang.ClassNotFoundException: software.amazon.awssdk.services.s3.S3Client
```

Adding `@CompileStatic` to groovy version will even not makes it possible to compile the class.
You'll get this error message from compiler:

```
The type software.amazon.awssdk.services.s3.S3Client cannot be resolved. It is indirectly referenced from required .class files
```

If it will be helpful then I can create new project with _Minimal, Reproducible Example_.

**Comment by dharrigan** [comment]
Hi,

Release 7.0.1 is also affecting me and my Clojure code (I've commented in (using ;;) what it looks like as Java)

```
(defn ^:private flyway
  [datasource migration-locations]
  (Flyway. (doto ;; new Flyway(...) with FluentConfiguration() set as the constructor.
             (FluentConfiguration.) ;; new FluentConfiguration()
             (.dataSource datasource) ;; `.setDataSource(datasource)`
             (.locations (into-array migration-locations))))) ;; `.locations(migration-locations)
```

Results in this:

```
Syntax error (ClassNotFoundException) compiling . at (migration.clj:10:14).
software.amazon.awssdk.services.s3.S3Client
```

**Comment by Lyeeedar** [comment]
We are very sorry for this regression. Flyway 7.0.2 should fix the issue however, so could you please update and test it is all working again?

**Comment by dharrigan** [comment]
Hi,

Thank you for the quick turn around! I can confirm with `7.0.2`, my Clojure code is once again working, with no compilation errors :-) Well done! Thanks again!

-=david=-

**Comment by walery** [comment]
I can also confirm that groovy version works with version 7.0.2
Thank you Lyeeedar!
